@startuml
skinparam classAttributeIconSize 0

class WorldManager {
    + world_grid: WorldGrid
    --
    + place_building(building: Building)
    + place_path(path: Path)
    + place_scientist(scientist: Scientist)
}

class WorldGrid <<TileMapLayer>> {
    + scientist_spawn_position: Marker2D
    + scientist_container: Node2D
    + building_container: Node2D
    + plane: ScientistPlane
    + scientists_to_place: Scientist[*]
    --
    + get_scientist_spawn_position(): Vector2
    + add_scientist(scientist_scene: Scientist)
    + add_building(building_scene: Building)
    - _on_make_scientist()
    - _restart_animation()
}

class Scientist {
    + speed: float
    + target_building: Building
    --
    + move_to(position: Vector2)
    + enter_building(building: Building)
}

class Building {
    + capacity: Integer
    + current_scientists: Integer
    --
    + emit_particles()
    + is_full(): Boolean
    + add_worker()
}

class BuildingScience {
    + door
    + science_per_second
    + nb_scientists_working
    + nb_scientists_slots
    + projects_list
    + text
    --
    + _init()
    + set_projects()
    + set_nbr_scientist_slots()
    + add_scientist()
    + remove_scientist()
    + scientists_add_slots()
    + building_get_type()
    + change_science_per_second_production()
    + get_project_list()
    + get_nbr_scientist()
    + get_nbr_scientist_max()
    + get_science_production()
    + get_science_production_ratio()
    + get_infos()
}

class WorldGrid {
    + scientist_spawn_position
    + scientist_container
    + building_container
    + plane
    + scientists_to_place
    + plane_spawn
    --
    + _ready()
    + get_scientist_spawn_position()
    + add_scientist()
    + _on_make_scientist()
    + add_building()
    + _restart_animation()

}

class ButtonBuildings {
    + textBuildingName
    + icon_pos
    + btype
    + nine_patch_rect
    + btn_crea_building
    + lbl_desc
    + notif
    + building_path
    + building_scene
    + building_instance
    + is_buyable
    + atlas
    + atlas
    + atlas
    --
    + set_button_icon_nor()
    + set_button_icon_pressed()
    + set_button_icon_hovered()
    + _process()
    + _ready()
    + _on_button_mouse_entered()
    + _on_button_mouse_exited()
    + _on_button_pressed()
}

class Path {
    + sprite_2d
    + gauche
    + haut
    + droite
    + bas
    + collisions_detected
    + value
    --
    + _ready()
    + _on_area_changed()
    + _on_update_sprite()
    + check_collision()
    + encode_collisions()
    + get_preview()
    + delete()
}

class BuildPlacement {
    + animation
    + preview
    + door
    + effect_size
    + in_placement
    + in_path_placement
    + can_be_placed
    + building_data
    + path_data
    + animation_playing
    + n_path
    + in_delete_object
    + placement_position
    + cell_array
    + is_dragging_path
    + path_start_pos
    + path_preview_cells
    + door_offset
    + sprite_node
    + door_node
    + building_zone
    + mouse_pos_glob
    + mouse_pos_grid
    + tile_under_mouse
    + world_grid_pos
    + rotated_offset
    + tile_under_mouse
    + size
    + start_x
    + end_x
    + start_y
    + end_y
    + pos
    + cell_world_pos
    + has_collision
    + is_adjacent_to_path
    + door_ok
    + shape
    + shape_transform
    + query
    + result
    + space_state
    + tile_size
    + directions
    + check_pos
    + query
    + result
    + instance
    + instance
    + space_state
    + cell_size
    + rect_shape
    + query
    + result
    + space_state
    + query
    + result
    + collision_mask
    + tile_under_mouse
    + tile_under_mouse
    + cells_in_l
    + cells
    + dx
    + dy
    + do_horizontal_first
    + current
    + step_x
    + step_y
    + step_y
    + step_x
    + has_connection
    + all_valid
    + cell_world_pos
    + is_existing_path
    + has_obstacle
    + placed_count
    + cell_world_pos
    + instance
    + mouse_pos
    + space_state
    + query
    + result
    + clicked
    --
    + _ready()
    + _input()
    + _on_building_signal()
    + start_building()
    + stop_building()
    + _update_mouse_positions()
    + _handle_rotation_input()
    + _handle_placement_preview()
    + _door_touches_path()
    + _is_adjacent_to_path()
    + _handle_building_click()
    + _clear_previous_preview()
    + _handle_animation_end()
    + _cell_collides()
    + _cell_has_path()
    + get_collision_layers_mask()
    + _on_path_button_pressed()
    + start_building_path()
    + stop_building_path()
    + build_path()
    + delete_object()
    + _handle_path_drag_input()
    + _update_path_l_preview()
    + _get_l_shaped_path()
    + _draw_path_preview()
    + _place_all_paths()
    + _handle_delete_object()
}

class Gauges {
    + science
    + science_per_seconds
    + pollution
    + max_pollution
    + pollution_per_seconds
    + wellness
    + wellness_min
    + wellness_max
    --
    + get_science()
    + change_science()
    + get_science_per_second()
    + change_science_per_second()
    + get_pollution()
    + get_pollution_per_second()
    + change_pollution()
    + change_pollution_per_second()
    + set_pollution_per_second()
    + get_wellness()
    + change_wellness()
    + update_gauges()
}

class BuildingFactory {
    + data
    + scene
    --
    + create_building()
    + get_preview_texture()
}

class PathFactory extends Node {
    + PATH_SCENE : String
    --
    + create_path()
}

class ScientistPlane {
    + anim
    + scientist_spawn_pos
    + signal_emited
    + audio
    --
    + _ready()
    + start_animation()
    + _process()
}

' MEOW
class ButtonCategory {
    + textBuildingName : String
    + textPopup : String
    + icon_pos : Vector2
    + btn_crea_building : Button
    + lbl_desc : Label
    + nine_patch_rect : NinePathRect
    + popup :Popup
    + notif
    + alreadyCliked : NotificationIndicator
    --
    + set_button_icon_nor()
    + set_button_icon_pressed()
    + set_button_icon_hovered()
    + _ready()
    + _on_button_mouse_entered()
    + _on_button_mouse_exited()
    + _on_button_pressed()
    + afficherPopup()
    + get_children_of_children(): Node[*]
    + get_category_container():Node
}

class BuildingManager {
    + buildingsIds : Integer[*]
    + building_counter : Integer
    + buildings_positions : Integer[*]
    +building_descriptions:String[*]
    --
    + create_building() : Building
    + create_path() : Path
    + register()
    + unregister()
    + get_building() : Building
    + get_building_list() : Building[*]
    + get_random_building_position() : Vector2
    + get_building_description() : String
    + get_free_spaces() : Integer
}
BuildingManager "1" --> "1 +building_factory" BuildingFactory
BuildingManager "1" --> "1 +PathFactory" PathFactory
BuildingManager "1" --> "1 +hovered_building" Building
BuildingManager "1" --> "* +buildings_list[*]" Building

class ScientistFactory {
    + SCIENTIST_PATH : String
    --
    + make_scientist():Scientist
}

class Project {
    + project_name : String
    + project_id : Integer
    + project_description : String
    + project_state : Integer
    + requirement_scientists : Integer
    + project_time : Integer
    + failure_chances : Integer
    + reward_science : Integer
    + reward_production : Integer
    + reward_slots : Integer
    + reward_pollution : Integer
    + reward_pollution_per_second : Integer
    + reward_wellness : Integer
    --
    + set_building()
    + console()
    + copy() : Project
    + start()
    + pause()
    + finish()
    + get_time_total() : Integer
    + get_project_name() : String
    + get_description() : String
    + get_project_state(): Integer
    + set_time()
}
Project "1" --> "* +building[*]" BuildingScience



class SettingsMenu {
    + resolution_option_button : OptionButton
    + master_volume : HSlider
    + sfx_volume : HSlider
    + music_volume : HSlider
    + fullscreen_chk : HSlider
    --
    + add_resolutions()
    + update_button_values()
    + _on_option_button_item_selected()
    + center_window()
    + _on_v_sync_toggled()
    + _on_mousse_toggled()
    + _on_fullscreen_toggled()
    + _on_h_slider_value_changed()
    + _on_sfx_volume_value_changed()
    + _on_music_volume_value_changed()
    + close_menu()
    + _on_back_to_game_btn_pressed()
    + _on_quit_game_btn_pressed()
}


class ProjectsManager {
    + get_list() : Project[*]
}
ProjectsManager "1" --> "* +list_icemine" Project
ProjectsManager "1" --> "* +list_glaciology" Project
ProjectsManager "1" --> "* +list_atmospheric" Project
ProjectsManager "1" --> "* +list_magnetism" Project
ProjectsManager "1" --> "* +list_biology" Project
ProjectsManager "1" --> "* +list_greenhouse" Project


class Scientist {
    + navigation_agent : NavigationAgent2D
    + animation_player : AnimationPlayer
    + speed : Integer
    + hours_in_same_building : Integer
    + can_change_target : Boolean
    + current_animation : String
    --
    + _physics_process()
    + play_animation()
    + _on_new_hour()
    + want_to_change() : Boolean
    + _on_navigation_agent_2d_navigation_finished()
    + change_target()
    + get_random_building_position() : Vector2
    + setTextureSprite()
}

Scientist ..> UiController

class MainMenu {
    + quit_game_btn : Button
    + settings_btn : Button
    + start_game_btn : Button
    + tutorial : Tutorial
    + hover_scale : Vector2
    --
    + init_pivot()
    + _start_button_enter()
    + _start_button_exit()
    + _settings_button_enter()
    + _settings_button_exit()
    + _quit_button_enter()
    + _quit_button_exit()
    + _start_game()
    + _quit_game()
}

class TimeManager {
    + current_time : Integer
    + next_hour : Integer
    + time_speed : Integer
    + day_length : Integer
    --
    + process_time()
    + get_time_hours()
    + get_time_minutes()
    + get_formatted_time() : String
}

class NotificationIndicator {
    + label : Label
    --
    + setVisible() : Boolean
    + set_text()
}

class ScientistManager {
    + scientist_total : Integer
    + scientist_occupied : Integer
    + scientist_price_factor : Integer
    + scientist_price : Integer
    + scientist_wellness_cost : Integer
    + scientist_pollution_travel : Integer
    + scientist_pollution_per_second : Integer
    --
    + enroll_scientist() : Scientist
    + assign_scientist()
    + deassign_scientist()
    + change_scientists_assigned()
    + get_scientist_total(): Integer
    + get_scientist_occupied(): Integer
    + enough_scientist_for_assignement() : Boolean
    + get_scientist_non_occupied() :Integer
    + get_scientist_price() : Integer
    + get_scientist_pollution_travel() : Integer
    + get_scientist_pollution_per_second() : Integer
    + change_scientist_pollution_per_second()
    + change_scientist_pollution_travel()
    + increase_price()
}
ScientistManager "1" --> "1 +scientist_factory" ScientistFactory
ScientistManager ..> UiController

class Building {
    + particles : GPUParticles2D
    + building_zone :CollisionShape2D
    + scientist_places : Integer
    + id : Integer
    + building_name : String
    + building_description : String
    + building_genre : BUILDING_GENRE
    + building_type : BUILDING_TYPE
    + pollution_per_second :Integer
    + price : Integer
    + mouse_hover : Boolean
    + wellness_value : Integer
    --
    + get_id() : Integer
    + set_id(new_id : Integer)
    + get_building_name(): String
    + get_building_type() : BUILDING_TYPE
    + get_pollution() : Integer
    + change_pollution(value : float)
    + delete()
    + _input()
    + _on_mouse_entered()
    + _on_mouse_exited()
    + get_door_position() :Vector2
    + emit_particles()
    + _on_gpu_particles_2d_finished()
    + get_infos() : String
}
Building ..>UiController: emit signal

class ButtonPath {
    + textBuildingName : String
    + icon_pos : Vector2
    + btn_crea_building : Button
    + lbl_desc : Label
    + nine_patch_rect : NinePatchRect
    + popup : Popup
    + notif : NotificationIndicator
    + alreadyCliked : Boolean
    --
    + set_button_icon_nor()
    + set_button_icon_pressed()
    + set_button_icon_hovered()
    + _ready()
    + _on_button_mouse_entered()
    + _on_button_mouse_exited()
    + _on_button_pressed()
}
ButtonPath ..>UiController: emit signal

class Game extends Node2D{
}
Game "1" -->"1 -world_grid" WorldGrid
Game "1" -->"1 -path" Path

class GameController <<Autoload>> extends Node{
    + START_SCIENCE : Integer
    + game_started : Boolean
    + update_time : Float
    --
    + set_grid(grid: TileMapLayer)
    + _on_build_batiment(bname : BUILDING_TYPE)
    + _on_build_path()
    + _on_validate_building_placement(building : Building)
    + _on_delete_building(building: Building)
    + _on_enroll_scientist()
    + _on_assign_scientist()
    + _on_deassign_scientist()
    + enough_scientist_for_assignement(n_scientist: Integer) : Boolean
    + get_scientist_total() : Integer
    + get_scientist_occupied() : Integer
    + get_gauges() : Gauges
    + get_building_manager() : BuildingManager
    + get_projects_manager() : ProjectsManager
    + notify_scientist_new_hour(hour: Integer)
    + get_random_building_position() : Vector2
    + get_all_buildings() : Building[]
    + get_building_description(btype: BUILDING_TYPE)
    + _update_gauges() 
    + pay_scientist() : Integer
    + init_default(world_grid: TileMapLayer)
}

class UiController <<Autoload>> extends Node{
    + build_batiment : Signal
    + start_building : Signal
    + start_placing_path : Signal
    + start_delete_object : Signal
    + validate_building_placement : Signal
    + validate_placing_path : Signal
    + delete_building : Signal
    + enroll_scientist : Signal
    + assign_scientist : Signal
    + deassign_scientist : Signal
    + update_assign_scientist : Signal
    + update_deassign_scientist : Signal
    + display_building_basic_info : Signal
    + new_hour : Signal
    + zoom_building : Signal
    + ui_change_category : Signal
    + science_changed : Signal
    + science_second_changed : Signal
    + pollution_changed : Signal
    + wellness_changed : Signal
    + lock_scroll_cam : Signal
    + click_on_building : Signal
    + close_menu_building : Signal
    + open_project_menu : Signal
    + start_project : Signal
    + project_change_state : Signal
    + stop_building_path : Signal
    + stop_building_bat : Signal
    + trigger_end_game : Signal
    --
    + emit_signal()
}

class SettingsValue <<Autoload>> extends CanvasLayer{
    + gui_components : String[]
    + Moove : MouseButton
    + Pos : MouseButton
    + resolutions : String[]
    --
    + open()
}

enum BUILDING_TYPE {
	LABORATORY_GLACIOLOGY
	LABORATORY_ATMOSPHERIC_PHYSICS
	LABORATORY_MAGNETISM_SEISMOLOGY
	LABORATORY_HUMAN_BIOLOGY
	ICEMINE
	GREENHOUSE
	DORMITORY
	CANTEEN
	SHOWER
	TOILET
	LOUNGE
	GYM
	WASTE_SORTING
	WATER_RECYCLING
	POWER_PLANT
	PATH
	NONE
}

enum BUILDING_GENRE { 
	SCIENCE
	UTILITY 
}

class AddScientistToBuilding extends MarginContainer {
    + BatScene : scene
    + bat_container : VBoxContainer
    + arrayBats : Building[*]
    --
    + _on_visibility_changed()
    + _update_build_list(new_buiding : Building)
    + add_bat_to_list(building : Building)
}



class BuildingUI extends MarginContainer {
    + projectScene : scene
    + menu_batiment : MarginContainer
    + buil : Building
    + project_menu_list : Project[*]
    + project_ui_list : SubProject[*]
    --
    + _on_click_on_building(building : Building)
    + _on_project_change_state(proj : Project)
    + _on_close_building_menu()
    + _on_btn_expl_pressed()
    + _on_btn_add_pressed()
    + _on_btn_rem_pressed()
    + _on_btn_quit_pressed()
}

class Gauges extends Control {
    + welness_bar : ProgressBar
    + pollution_bar : ProgressBar
    --
    + _on_wellness_changed(wellness : Float)
    + _on_pollution_changed(pollution : Float)
    + _on_progress_bar_mouse_entered()
    + _on_progress_bar_mouse_exited()
    + _on_progress_bar_mouse_entered()
    + _on_pollution_bar_mouse_exited()
}

class MainUI extends Control {
    + _on_button_projects_pressed()
    + _on_button_scientists_pressed()
    + _on_science_changed(new_science : Float)
    + _on_science_second_changed(new_science : Float)
    + _on_not_enough_science()
    + _handle_category_changed(cat_num : int)
    + btn_cat_1_pressed()
    + btn_cat_2_pressed()
    + btn_cat_3_pressed()
    + _on_btn_back_pressed()
    + _on_parameters_pressed()
    + endscreendisplay()
}

class PopupDescBuildings extends Popup {
    + lbl_desc : Label
    --
    + setDesc(text : String)
}

class ProjectUI extends MarginContainer {
    + arrayProjects : Project[*]
    --
    + _on_start_project(project : Project)
    + _on_btn_close_projects_pressed()
    + _on_btn_close_projects_mouse_entered()
    + _on_btn_close_projects_mouse_exited()
    + _on_visibility_changed()
}

class ShowProjectInfos extends MarginContainer {
    + project : Project
    --
    + _on_open_project_menu(proj : Project)
    + setStatus(statusValue : int)
    + setVisiility(vis : Boolean)
    + _on_btn_start_pressed()
    + _on_btn_quit_pressed()
    + _on_btn_start_mouse_entered()
    + _on_btn_start_mouse_exited()
}

class SubAddScientistToBuilding extends MarginContainer {
    + buil : Building
    --
    + setName(text : String)
    + setVisibility(vis : Boolean)
    + setBuilding(building : Building)
    + _on_assigantion_pressed()
    + _on_deassigantion_pressed()
}

class SubProject extends MarginContainer {
    + project : Project
    + project_started : Boolean
    --
    + setProject(proj : Project)
    + getProject() : Project
    + instanciateProject()
    + setStatus(statusValue : int)
    + setVisibility(vis : Boolean, timer_displayed : Boolean)
    + startProject()
    + _on_button_pressed()
    + _on_button_mouse_entered()
    + _on_button_mouse_exited()
}

class Tutorial extends Control{
    + game_scene : scene
    + images : String[]
    + images_short : String[]
    + explanations : String[]
    + explanations_short : String[]
    + index : int
    --
    + show_image(i : int)
    + _on_next_btn_pressed()
    + _on_back_btn_pressed()
    + _on_skip_btn_pressed()
}



Node <|-- Control
Node <|-- CanvasLayer
Node <|-- Popup
Node <|-- Node2D
Node2D <|-- Area2D
Node2D <|-- CharacterBody2D
Node2D <|-- TileMapLayer

Node <|-- WorldManager
Node <|-- BuildingManager
Node <|-- ProjectsManager
Node <|-- TimeManager
Node <|-- ScientistManager

Node <|-- Gauges
Node <|-- Project

Node <|-- ScientistFactory
CharacterBody2D <|-- Scientist

Node <|-- BuildingFactory
Area2D <|-- Building
Building <|-- BuildingScience
TileMapLayer <|-- BuildPlacement

Area2D <|-- Path

Control <|-- MainMenu
Control <|-- NotificationIndicator
Control <|-- ButtonCategory
Control <|-- ButtonBuildings
Control <|-- SettingsMenu
Control <|-- ButtonPath
Control <|-- MarginContainer

MarginContainer <|-- ScientistMenu

TileMapLayer <|-- WorldGrid
Node2D <|-- ScientistPlane

WorldManager "1" *-- "1" WorldGrid
WorldGrid "1" *-- "*" Scientist
WorldGrid "1" *-- "*" Building
ScientistMenu ..> WorldManager : triggers recruitment

GameController "1" *-- "1" TimeManager
GameController "1" *-- "1" WorldManager
GameController "1" *-- "1" BuildingManager
GameController "1" *-- "1" ProjectsManager
GameController "1" *-- "1" ScientistManager
GameController "1" *-- "1" Gauges

Game ..> GameController : init game
Gauges ..> GameController
Project ..> GameController
TimeManager ..> GameController
BuildingManager ..> GameController
ScientistManager ..> GameController 

GameController <..> UiController : transfer signals

Building ..> UiController  : emit signals
BuildPlacement ..> UiController : emit signals
Gauges ..> UiController : emit signals
Scientist ..> UiController : connect to signals
ScientistManager ..> UiController : emit signals

WorldManager ..> Building : place
WorldManager ..> Path : place
WorldManager ..> Scientist : place

BuildingFactory ..> Building : instantiate
PathFactory ..> Path : instantiate
ScientistFactory ..> Scientist : instantiate

Building ..> BUILDING_GENRE : uses
Building ..> BUILDING_TYPE : uses

BuildPlacement ..> Building
BuildPlacement ..> Path

Project ..> BuildingScience

WorldGrid ..> Building : place
WorldGrid ..> Scientist : place

buttonCategory  ..> UiController : emit signals


@enduml
